# Generated by Django 2.2 on 2022-05-10 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=1000)),
                ('time_created', models.DateTimeField(default=datetime.datetime(2022, 5, 10, 11, 9, 36, 898144))),
            ],
        ),
    ]
